# -*- coding: utf-8 -*-
from django.conf.urls import url, patterns

from . import views
from .views import api
from .views.api import generic
from .views import admin, club, player


urlpatterns = [
    # TODO: move to separate namespace
    # REST API
    url(r'^api/countries/$', generic.CountryList.as_view(),
        name='country-list-api'),
    url(r'^api/countries/leagues/$', generic.CountryLeagueList.as_view(),
        name='country-league-list-api'),
    url(r'^api/leagues/$', generic.LeagueList.as_view(),
        name='league-list-api'),
    url(r'^api/players/$',
        api.PlayersSearch.as_view({'get': 'list'}),
        name='players-search-api'),
    url(r'^api/players/best/$',
        api.BestPlayer.as_view({'get': 'retrieve'}),
        name='best-player-api'),
    url(r'^api/players_by_name/$',
        api.PlayerNamesSearch.as_view(),
        name='player-names-search-api'),
    url(r'^api/clubs_by_title/$',
        api.ClubTitlesSearch.as_view(),
        name='club-titles-search-api'),
    url(r'^api/players/(?P<pk>\d+)/$',
        api.PlayersSearch.as_view({'get': 'retrieve'}),
        name='player-card-api'),
    url(r'^api/players/(?P<player_id>\d+)/indicators/$',
        api.PlayerCardIndicators.as_view(),
        name='player-card-indicators-api'),
    url(r'^api/players/(?P<pk>\d+)/timeline/$',
        api.PlayerTimeline.as_view(),
        name='player-timeline-api'),
    url(r'^api/clubs/(?P<pk>\d+)/$', api.ClubTeam.as_view(),
        name='club-team-api'),
    url(r'^api/clubs/(?P<pk>\d+)/compare/$', api.ClubTeamCompare.as_view(),
        name='club-team-compare-api'),
    url(r'^api/clubs/(?P<pk>\d+)/calendar/$', api.ClubCalendar.as_view(),
        name='club-calendar-api'),
    url(r'^api/metrics/$', api.MetricsPlayers.as_view(),
        name='metrics-list-api'),
    url(r'^api/news/$', api.NewsList.as_view(), name='news-list-api'),
    url(r'^api/schedule/(?P<pk>\d+)/$',
        api.ScheduleView.as_view(), name='schedule-api'),
    # Django CBV's'
    url(r'^$', views.Index.as_view(),
        name='index'),
    url(r'^classic/$', views.IndexClassic.as_view(),
        name='index-classic'),
    url(r'^pro/$', views.IndexPro.as_view(),
        name='index-pro'),
    # metrics
    url(r'^metrics/players/$', views.MetricsPlayers.as_view(),
        name='metrics-players'),
    url(r'^metrics/players/(?P<pk>\d+)/$', views.MetricsPlayerCard.as_view(),
        name='metrics-player-card'),
    url(r'^metrics/players/compare/$', views.MetricsPlayersCompare.as_view(),
        name='metrics-compare'),
    url(r'^metrics/players/compare/graph/$',
        views.MetricsPlayersCompareGraph.as_view(),
        name='metrics-compare-graph'),
    # players
    url(r'^players/$', player.PlayersSearch.as_view(),
        name='players-search'),
    url(r'^players2/$', player.PlayersSearch2.as_view(),
        name='players-search2'),
    url(r'^players/(?P<pk>\d+)/$', player.PlayerCard.as_view(),
        name='player-card'),
    url(r'^players/(?P<pk>\d+)/indicators/$',
        player.PlayerCardIndicators.as_view(),
        name='player-card-indicators'),
    url(r'^players/(?P<pk>\d+)/clubs/$', player.PlayerCardClubs.as_view(),
        name='player-card-clubs'),
    url(r'^players/(?P<pk>\d+)/coaches/$', player.PlayerCardCoaches.as_view(),
        name='player-card-coaches'),
    url(r'^players/(?P<pk>\d+)/partners/$',
        player.PlayerCardPartners.as_view(),
        name='player-card-partners'),
    url(r'^players/(?P<pk>\d+)/photos/$', player.PlayerCardPhotos.as_view(),
        name='player-card-photos'),
    url(r'^players/(?P<pk>\d+)/communication/$',
        player.PlayerCardCommunication.as_view(),
        name='player-card-communication'),
    url(r'^players/(?P<pk>\d+)/news/$', player.PlayerCardNews.as_view(),
        name='player-card-news'),
    # clubs
    url(r'^clubs/$', club.ClubListView.as_view(), name='club-list'),
    url(r'^clubs/(?P<pk>\d+)/$', club.ClubView.as_view(), name='club'),
    url(r'^clubs/(?P<pk>\d+)/calendar/$', club.ClubCalendarView.as_view(),
        name='club-calendar'),
    url(r'^clubs/(?P<pk>\d+)/stats/$', club.ClubStatsView.as_view(),
        name='club-stats'),
    url(r'^clubs/(?P<pk>\d+)/home/$', club.ClubHomeView.as_view(),
        name='club-home'),
    url(r'^clubs/(?P<pk>\d+)/photos/$', club.ClubPhotosView.as_view(),
        name='club-photos'),
    url(r'^clubs/(?P<pk>\d+)/fanzone/$', club.ClubFanZoneView.as_view(),
        name='club-fanzone'),
    url(r'^clubs/(?P<pk>\d+)/news/$', club.ClubNewsView.as_view(),
        name='club-news'),
    url(r'^clubs/(?P<pk>\d+)/numbers/$', club.ClubNumbersView.as_view(),
        name='club-numbers'),

    #admin
    url(r'^sporto-admin/club-insta-photo/$',
        admin.cpat,
        name='club-insta-photo'),
]
