# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views
from .views import api


urlpatterns = (
    # TODO: move to separate namespace
    # REST API
    url(r'^api/leagues/$', api.LeagueList.as_view(),
        name='league-list-api'),
    url(r'^api/players/$',
        api.PlayersSearch.as_view({'get': 'list'}),
        name='players-search-api'),
    url(r'^api/players_by_name/$',
        api.PlayerNamesSearch.as_view(),
        name='player-names-search-api'),
    url(r'^api/clubs_by_title/$',
        api.ClubTitlesSearch.as_view(),
        name='club-titles-search-api'),
    url(r'^api/players/(?P<pk>\d+)/$',
        api.PlayersSearch.as_view({'get': 'retrieve'}),
        name='player-card-api'),
    url(r'^api/players/(?P<player_id>\d+)/indicators/$',
        api.PlayerCardIndicators.as_view(),
        name='player-card-indicators-api'),
    url(r'^api/clubs/$', api.ClubList.as_view(),
        name='club-list-api'),
    url(r'^api/clubs/(?P<pk>\d+)/$', api.ClubTeam.as_view(),
        name='club-team-api'),
    url(r'^api/clubs/(?P<pk>\d+)/compare/$', api.ClubTeamCompare.as_view(),
        name='club-team-compare-api'),
    url(r'^api/metrics/$', api.MetricsPlayers.as_view(),
        name='metrics-list-api'),
    # Django CBV's'
    url(r'^$', views.Index.as_view(),
        name='index'),
    url(r'^classic/$', views.IndexClassic.as_view(),
        name='index-classic'),
    url(r'^pro/$', views.IndexPro.as_view(),
        name='index-pro'),
    # metrics
    url(r'^metrics/players/$', views.MetricsPlayers.as_view(),
        name='metrics-players'),
    url(r'^metrics/players/(?P<pk>\d+)/$', views.MetricsPlayerCard.as_view(),
        name='metrics-player-card'),
    url(r'^metrics/players/compare/$', views.MetricsPlayersCompare.as_view(),
        name='metrics-compare'),
    url(r'^metrics/players/compare/graph/$',
        views.MetricsPlayersCompareGraph.as_view(),
        name='metrics-compare-graph'),
    # players
    url(r'^players/$', views.PlayersSearch.as_view(),
        name='players-search'),
    url(r'^players/(?P<pk>\d+)/$', views.PlayerCard.as_view(),
        name='player-card'),
    url(r'^players/(?P<pk>\d+)/indicators/$',
        views.PlayerCardIndicators.as_view(),
        name='player-card-indicators'),
    url(r'^players/(?P<pk>\d+)/clubs/$', views.PlayerCardClubs.as_view(),
        name='player-card-clubs'),
    url(r'^players/(?P<pk>\d+)/coaches/$', views.PlayerCardCoaches.as_view(),
        name='player-card-coaches'),
    url(r'^players/(?P<pk>\d+)/partners/$', views.PlayerCardPartners.as_view(),
        name='player-card-partners'),
    url(r'^players/(?P<pk>\d+)/photos/$', views.PlayerCardPhotos.as_view(),
        name='player-card-photos'),
    url(r'^players/(?P<pk>\d+)/communication/$',
        views.PlayerCardCommunication.as_view(),
        name='player-card-communication'),
    url(r'^players/(?P<pk>\d+)/news/$', views.PlayerCardNews.as_view(),
        name='player-card-news'),
    # clubs
    url(r'^clubs/$', views.ClubListView.as_view(), name='club-list'),
    url(r'^clubs/(?P<pk>\d+)/$', views.ClubView.as_view(), name='club'),
    url(r'^clubs/(?P<pk>\d+)/calendar/$', views.ClubCalendarView.as_view(),
        name='club-calendar'),
    url(r'^clubs/(?P<pk>\d+)/stats/$', views.ClubStatsView.as_view(),
        name='club-stats'),
    url(r'^clubs/(?P<pk>\d+)/home/$', views.ClubHomeView.as_view(),
        name='club-home'),
    url(r'^clubs/(?P<pk>\d+)/photos/$', views.ClubPhotosView.as_view(),
        name='club-photos'),
    url(r'^clubs/(?P<pk>\d+)/fanzone/$', views.ClubFanZoneView.as_view(),
        name='club-fanzone'),
)
