server {
    listen 80;
    server_name khl.sportomatics.com www.sportomatics.ru localhost;

    location /media/ {
        alias /app/media/;
        expires 5d;
    }

    location /static/ {
        alias /app/static/;
        expires 5d;
    }

    location / {
        client_max_body_size 32m;
        proxy_pass http://web:8000;
        proxy_pass_header If-Modified-Since;
        proxy_set_header If-Modified-Since $http_if_modified_since;
        proxy_pass_header Server;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_connect_timeout 120s;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
